-- ══════════════════════════════════════════════════════════════════
-- Module 12 — Quiz d'évaluation finale
-- Module 13 — Clôture & Attestation de formation
-- ══════════════════════════════════════════════════════════════════

DO $m12$
DECLARE
  cid UUID;
  mid UUID;
BEGIN
  SELECT id INTO cid FROM academy_courses WHERE slug = 'fiber-signature' LIMIT 1;

  INSERT INTO academy_modules (course_id, title, sort_order)
  VALUES (cid, 'Quiz d''évaluation finale', 12)
  RETURNING id INTO mid;

  -- M12.L1 — Quiz — 20 questions tirées aléatoirement
  INSERT INTO academy_lessons (module_id, course_id, title, sort_order, duration_minutes, content_blocks)
  VALUES (mid, cid, 'Quiz — 20 questions tirées aléatoirement', 1, 45,
    $cb$[
      {"type":"text","content":"Comment ça fonctionne : 20 questions sont tirées aléatoirement parmi 41. Sélectionne ta réponse pour chaque question, puis valide pour voir ton score et les explications. Tu peux relancer un nouveau tirage à tout moment. Les tentatives sont illimitées.\n\nSeuil de validation du parcours pédagogique : 14/20 minimum. Ce seuil est un critère interne Nahira Academy — il ne constitue ni un diplôme, ni une certification professionnelle reconnue par une autorité publique."},
      {"type":"table","headers":["#","Question","Option A","Option B","Option C","Option D","Bonne réponse","Explication"],"rows":[
        ["1","Les temps de polymérisation indiqués dans cette formation sont :","Valables pour tous les systèmes de gel","À titre indicatif — ils dépendent du système et des instructions fabricant","Fixés à 60 secondes par couche pour la fibre de verre","Définis de façon universelle par la technique Fiber Signature","B","Règle permanente : les instructions du fabricant sont prioritaires sur toute recommandation générale. Les valeurs de la formation sont indicatives. (Module 4)"],
        ["2","Avant d'appliquer une couche de gel, la règle fondamentale est :","Laisser exactement 1 mm entre le gel et la cuticule","Appliquer un primer avant chaque couche","S'assurer qu'aucun produit n'entre en contact avec la peau","Polymériser la couche précédente 90 secondes","C","La marge de 0,5–1 mm est une référence pédagogique. Le principe fondamental est l'absence totale de contact entre le produit et la peau. (Module 4)"],
        ["3","Tu observes une tache verdâtre sous une pose. La conduite appropriée est :","Identifier une infection bactérienne et conseiller un traitement","Décrire le signe observé, ne pas poser sur cet ongle, orienter vers un professionnel de santé et évaluer l'ensemble des ongles","Nettoyer l'ongle avec de l'alcool et continuer la pose","Poser dessus car la cliente est régulière et le signe est habituel pour elle","B","Observer sans diagnostiquer. Le signe est décrit (coloration), la conduite est professionnelle (report, orientation). L'ensemble des ongles est évalué avant toute décision. (Module 9)"],
        ["4","Peut-on systématiquement réaliser la prestation sur les autres ongles si l'un présente un signe d'alerte ?","Oui, si les autres ongles semblent visuellement normaux","Non — l'ensemble de la situation et le risque de contamination croisée doivent être évalués avant toute décision","Oui, la cliente a signé la Fiche F3","Oui, si la cliente le demande expressément","B","Aucune décision automatique. L'évaluation globale et le risque de contamination croisée sont pris en compte avant de poursuivre. (Module 9 & Règle permanente 6)"],
        ["5","La position de l'apex dans une pose fibre de verre est :","Toujours au tiers médian vers le bord libre","Toujours au centre géométrique de l'ongle","Variable selon la longueur, la forme, l'architecture de l'ongle et le système utilisé","Définie uniquement par la marque de gel utilisée","C","La zone et le volume de l'apex dépendent de plusieurs facteurs — longueur, forme, architecture, système. Aucune position n'est universellement fixe. (Règle permanente 11)"],
        ["6","Les grains de lime utilisés dans la formation sont présentés comme :","Des valeurs universelles applicables à toutes les plaques et tous les matériels","Des valeurs à titre indicatif, à adapter selon le matériel et les recommandations fabricant","Des grains réglementaires imposés par les normes d'hygiène","Des valeurs identiques quelle que soit l'étape de la pose","B","Les grains sont indicatifs et s'adaptent au matériel utilisé et aux instructions fabricant. (Règle permanente 8 — Module 6)"],
        ["7","La Fiche F3 est :","Une obligation légale universelle dans tous les pays","Un document d'information et d'accord proposé par Nahira Academy — ses effets varient selon le cadre réglementaire applicable","Un certificat médical requis avant toute pose","Un document qui supprime la responsabilité professionnelle de la prestataire","B","La Fiche F3 est un outil de la démarche Nahira Academy, non une obligation légale universelle. Elle ne supprime pas les obligations professionnelles de la prestataire. (Règle permanente 13 — Module 10)"],
        ["8","Faire tremper les cuticules dans l'eau avant une pose en gel :","Est recommandé pour assouplir les cuticules et faciliter la préparation","Le trempage à l'eau n'est pas retenu comme protocole standard avant la pose — la plaque doit être correctement préparée et sèche selon le système utilisé et les instructions fabricant","Est obligatoire pour préparer la plaque correctement","Est recommandé uniquement pour les clientes ayant des cuticules très sèches","B","Le trempage à l'eau n'est pas un protocole standard avant la pose en gel. La plaque doit être préparée et sèche conformément au système utilisé et aux instructions fabricant. (Règle permanente 7)"],
        ["9","La base tarifaire calculée avec la méthode de la formation est :","Le tarif minimum universel sous lequel on travaille toujours à perte","Une base indicative de calcul — cotisations, taxes et prélèvements applicables restent à intégrer séparément selon le statut","Le tarif définitif à appliquer pour toutes les prestations","Identique pour toutes les professionnelles à niveau de compétence égal","B","La méthode donne une base pédagogique. Cotisations sociales, fiscalité, taxes et commissions sont à intégrer séparément selon le statut et le pays. (Module 10)"],
        ["10","Les instructions du fabricant sont-elles prioritaires sur les recommandations générales de la formation ?","Non — la formation Fiber Signature prévaut sur tout autre protocole","Oui — notamment pour les temps de polymérisation, les compatibilités et les protocoles d'application","Cela dépend de la marque et de l'année du produit","Non — les instructions fabricant sont indicatives comme celles de la formation","B","Règle permanente fondamentale : les instructions du fabricant sont prioritaires sur toute recommandation générale. (Règle permanente 3)"],
        ["11","Lors de la consultation initiale, comment formuler la question sur les médicaments ou traitements ?","\"Prenez-vous des médicaments photosensibilisants ?\"","\"Avez-vous des traitements en cours ?\" et analyser la réponse pour identifier les risques","\"Y a-t-il une recommandation médicale ou une information de votre médecin sur les soins esthétiques de vos ongles que vous souhaitez me communiquer ?\"","Ne pas aborder le sujet médical lors de la consultation","C","La prestataire ne doit pas interpréter des traitements médicaux. La question ouverte invite la cliente à communiquer une recommandation de son médecin. (Module 11)"],
        ["12","Un retour négatif d'une cliente après une pose doit être traité :","Comme une erreur nécessairement imputable à la prestataire","Comme une faute de la cliente liée à ses habitudes","En distinguant les éléments pouvant être liés à la prestation, les facteurs extérieurs déclarés, et l'origine indéterminée ou multifactorielle","Par une retouche gratuite systématique pour éviter le conflit","C","Trois catégories à distinguer : lié à la prestation / extérieur déclaré ou observable / origine indéterminée. Aucune attribution automatique de cause. (Module 11)"],
        ["13","La formule d'annonce d'un refus de prestation se fait en :","1 temps : annoncer le refus directement et sans détail","3 temps : décrire ce qu'on observe · expliquer la décision · proposer la suite","2 temps : annoncer le refus et s'excuser","4 temps : observer · nommer le signe · décider · orienter","B","La formule en 3 temps permet d'annoncer calmement, sans alarmer ni minimiser, et de proposer une suite concrète. (Module 11)"],
        ["14","La \"majoration de sécurité\" dans le calcul de tarif couvre :","Les cotisations sociales, la fiscalité et les taxes éventuelles","Les imprévus, le renouvellement matériel, la formation continue et la variation d'activité","L'ensemble des prélèvements obligatoires liés à l'activité","Le bénéfice net de l'activité","B","Les cotisations, taxes et commissions sont à intégrer séparément selon le statut et le pays — elles ne font pas partie de la majoration de sécurité. (Module 10)"],
        ["15","Quand une retouche est-elle une obligation professionnelle plutôt qu'un geste commercial ?","À chaque retour d'une cliente dans les 15 jours suivant la pose","Lorsqu'un défaut clairement imputable à la prestation est établi","Dès que la cliente exprime une insatisfaction","Après chaque première pose, indépendamment du résultat","B","Corriger un défaut établi côté prestation est une obligation — pas un geste commercial. Le geste commercial s'applique lorsque l'origine est incertaine. (Module 11)"],
        ["16","Le top coat et la couche de scellement :","Sont toujours interchangeables dans tous les systèmes","Ont toujours des rôles strictement différents selon une règle universelle","Ont des rôles qui dépendent du système utilisé — consulter les instructions fabricant","Servent uniquement à la finition esthétique, sans rôle structurel","C","Leur rôle (construction, finition, protection) varie selon le système. Les instructions fabricant précisent lequel utiliser à quelle étape. (Règle permanente 14)"],
        ["17","Face à un avis négatif en ligne, la conduite professionnelle est de :","Répondre en détaillant les raisons médicales du refus de prestation effectué","Répondre brièvement et calmement, sans révéler d'informations issues de la fiche cliente, et proposer une solution en privé","Ignorer l'avis pour ne pas lui donner de visibilité","Demander à des proches de publier des avis positifs pour compenser","B","La confidentialité des données de la fiche cliente s'applique aussi en ligne. La réponse est calme, factuelle, sans détail personnel. (Module 11)"],
        ["18","L'accord pour photographier une pose et l'autorisation de publier l'image sont :","Identiques — l'un inclut automatiquement l'autre","Deux consentements distincts à obtenir séparément selon le droit applicable","Couverts dans tous les cas par la signature de la Fiche F3","Non nécessaires si la cliente est satisfaite du résultat","B","Photographier pour la fiche cliente ne donne pas le droit de publier. Ces deux consentements sont distincts et doivent être obtenus séparément. (Module 11)"],
        ["19","Le \"chiffre d'affaires horaire moyen\" (CA ÷ heures travaillées) :","Est équivalent au revenu net horaire de la prestataire","Mesure le CA généré par heure — les charges, cotisations et taxes restent à déduire pour obtenir un revenu net","Suffit seul à évaluer la rentabilité de l'activité","Est le bénéfice avant impôts","B","Ce ratio mesure le CA horaire moyen — il ne reflète pas le revenu net. Les charges et prélèvements applicables restent à déduire. (Module 10)"],
        ["20","Un consommable (compresse, applicateur) utilisé sur un ongle peut-il servir sur un autre ?","Oui, s'il est désinfecté à l'alcool entre les deux","Non pour les consommables à usage unique — principe de prévention de la contamination croisée","Oui si la cliente est régulière et ne présente pas de signe d'alerte","Oui si la prestation se déroule sans incident","B","La prévention de la contamination croisée impose l'usage unique pour les consommables concernés. (Module 3 — Règle permanente 10)"],
        ["21","La durée d'une prestation en pose fibre de verre est :","Toujours comprise entre 1h30 et 2h30","Variable selon le type de pose, l'état de la pose existante et le niveau de la professionnelle","Fixée à 2h pour un rééquilibrage, quelle que soit la situation","La même pour toutes les professionnelles certifiées Fiber Signature","B","La durée varie selon plusieurs facteurs. Chronométrer ses propres prestations est la méthode pour ajuster le planning. (Module 10 & 11)"],
        ["22","La consultation initiale sert principalement à :","Choisir la couleur et la forme de la pose le plus vite possible","Recueillir les informations nécessaires, identifier les points de vigilance, définir l'objectif esthétique et établir la confiance","Remplir la Fiche F3 en moins de 5 minutes avant de commencer","Convaincre la cliente de choisir la prestation la plus complète","B","La consultation est un moment structurant : elle oriente toutes les décisions techniques qui suivent. (Module 11)"],
        ["23","La marge de 0,5 à 1 mm entre le gel et la peau est présentée comme :","Une garantie absolue d'adhérence et de tenue de la pose","Une référence pédagogique — le principe fondamental reste l'absence totale de contact produit/peau","La distance réglementaire imposée par les normes d'hygiène","Une marge universelle valable pour tous les systèmes de gel","B","La marge est une référence pédagogique. L'absence de contact entre le produit et la peau est le principe fondamental, indépendamment de la distance. (Règle permanente 9)"],
        ["24","Face à une cliente qui minimise un signe d'alerte (\"j'ai toujours eu ça\"), on :","Accepte sa perception et réalise la prestation pour ne pas la décevoir","Maintient sa décision professionnelle — la cliente informe de sa perception, mais l'évaluation reste la responsabilité de la prestataire","Consulte une autre professionnelle présente pour se rassurer","Documente le refus de la cliente et réalise la prestation sous sa propre responsabilité","B","L'information de la cliente est utile mais ne se substitue pas à l'évaluation technique. La décision professionnelle reste celle de la prestataire. (Module 11)"],
        ["25","Le traitement de la couche inhibée après polymérisation dépend :","Toujours d'un essuyage avec un gel cleanser avant toute couche suivante","Toujours de la laisser telle quelle car elle favorise l'adhérence","Du système utilisé — consulter les instructions fabricant pour savoir comment la traiter","De la marque de lampe utilisée pour la polymérisation","C","Le traitement de la couche inhibée varie selon le système. Les instructions fabricant indiquent si elle doit être essuyée ou non avant la couche suivante. (Module 4)"],
        ["26","Une politique de retouche écrite et communiquée à l'avance :","Garantit que la cliente ne pourra jamais réclamer de retouche gratuite","Écarte automatiquement la responsabilité de la prestataire pour tout soulèvement","Réduit les situations ambiguës en établissant à l'avance ce qui est couvert","Est une obligation légale dans tous les pays pour les prestations esthétiques","C","La politique de retouche réduit les ambiguïtés — elle ne supprime pas les obligations en cas de défaut de pose établi. (Module 11)"],
        ["27","Le principe de minimisation des données personnelles signifie :","Ne jamais collecter d'informations sur les clientes","Ne collecter que les informations strictement nécessaires à la compatibilité avec la technique et au suivi de la prestation","Réduire la durée de la fiche cliente à une seule page","Ne pas enregistrer les observations négatives sur la plaque naturelle","B","Minimiser les données réduit les risques liés à leur conservation et facilite la gestion conforme. Cela n'empêche pas de documenter les observations utiles. (Module 10)"],
        ["28","Lors d'un retour lié à un soulèvement, les questions posées à la cliente doivent :","Suggérer des causes possibles pour guider sa réponse","Être ouvertes et ne pas orienter la réponse de la cliente","Confirmer que la cause est extérieure à la prestation","Être posées après avoir établi la cause par l'observation seule","B","Les questions ouvertes permettent à la cliente de répondre librement, sans orienter sa réponse vers une cause présupposée. (Module 11)"],
        ["29","Documenter les observations et décisions sur la fiche cliente après chaque prestation :","N'est utile qu'en cas de litige ou de réclamation ultérieure","Protège automatiquement la prestataire contre toute réclamation","Permet le suivi technique et la traçabilité professionnelle à chaque visite","Est uniquement une obligation administrative sans valeur professionnelle","C","La documentation régulière assure la traçabilité professionnelle et permet d'adapter les décisions à l'historique de la cliente — au-delà du seul cas de litige. (Module 10)"],
        ["30","Le délai entre une pose et un retour cliente :","Détermine automatiquement si la prestataire est responsable ou non","Écarte automatiquement la responsabilité de la prestataire si le délai est long","Est un élément d'évaluation parmi d'autres — il ne détermine pas seul la cause du problème","Prouve que la pose était de mauvaise qualité si le retour survient rapidement","C","Le délai est un élément d'évaluation, pas une preuve de cause. L'analyse honnête prend en compte l'ensemble du tableau. (Module 11)"],
        ["31","Les obligations d'affichage des tarifs :","Sont identiques dans tous les pays et pour tous les statuts","Imposent toujours d'afficher un tarif fixe et unique sans fourchette possible","Varient selon le statut, le lieu d'exercice et la réglementation applicable — à vérifier selon sa situation","Ne s'appliquent qu'aux salons de beauté disposant d'une enseigne commerciale","C","Les obligations varient selon le statut et le pays. La bonne pratique est de communiquer le prix clairement avant tout engagement. (Module 10)"],
        ["32","Pour une prestation sur une plaque présentant des particularités observées, la conduite est :","Refuser systématiquement toute pose sur cette plaque","Évaluer la compatibilité avec la technique, adapter le protocole si possible, ou reporter si nécessaire","Réaliser la pose standard en informant la cliente des risques par écrit","Appliquer une couche de primer supplémentaire pour compenser","B","L'évaluation de la compatibilité précède la décision. Selon l'état de la plaque, la prestation peut être adaptée, reportée ou refusée. (Module 9)"],
        ["33","\"Renforcement sans allongement\" est une prestation :","Identique à une première pose en termes de protocole","Adaptée à l'état de la plaque et à la compatibilité avec la technique choisie — à distinguer de la première pose","Réservée aux clientes ayant des ongles médicalement fragiles","Toujours réalisable sur toutes les plaques sans adaptation particulière","B","Cette prestation est définie par l'état observé de la plaque et la compatibilité avec la technique — pas par un critère médical. (Module 10)"],
        ["34","Un gel rubber base et un primer :","Ont le même rôle et sont interchangeables dans tous les systèmes","Sont deux noms commerciaux différents pour le même produit","Ont des rôles et des protocoles d'application distincts qui varient selon les systèmes — suivre les instructions fabricant","Servent uniquement à préparer la plaque naturelle avant le gel de construction","C","Leurs rôles, compatibilités et protocoles varient selon les systèmes. Les instructions fabricant sont la référence. (Module 2)"],
        ["35","Lors d'une réclamation, la première étape du protocole est :","Observer l'ongle pour identifier la cause avant toute conversation","Expliquer à la cliente ce qui s'est probablement passé","Écouter sans interrompre — laisser la cliente s'exprimer complètement avant de répondre","Proposer une retouche immédiate pour désamorcer le conflit","C","Écouter d'abord — avant d'observer, analyser ou proposer. La cliente doit pouvoir s'exprimer complètement. (Module 11)"],
        ["36","L'accord de la cliente (Fiche F3 ou accord verbal) :","Supprime les obligations professionnelles de la prestataire","Autorise à réaliser une prestation qui présente un signe d'alerte si la cliente accepte le risque","Ne supprime pas les obligations professionnelles — la décision technique reste la responsabilité de la prestataire","Remplace l'évaluation clinique préalable à la pose","C","L'accord de la cliente n'est pas un blanc-seing. La décision de réaliser ou non la prestation reste celle de la prestataire, indépendamment de l'accord signé. (Module 10)"],
        ["37","La construction de l'apex dans une pose fibre de verre :","Suit la règle universelle : plus d'apex = plus de résistance","Doit être proportionnelle à la longueur de l'ongle, à son architecture et au système utilisé","Est fixée à un volume standard quelle que soit la longueur","Ne joue aucun rôle dans la durabilité de la pose","B","L'architecture de l'apex doit être proportionnelle à la situation — un apex excessif peut fragiliser plutôt que renforcer. (Règle permanente 12)"],
        ["38","Le placement de la fibre de verre pendant la pose dépend :","D'une règle universelle fixée par la formation Fiber Signature","Uniquement de la longueur d'ongle souhaitée","Du système utilisé et des instructions fabricant — le protocole exact varie","De la préférence de chaque professionnelle sans contrainte particulière","C","La couche sur laquelle la fibre est posée, son imprégnation et sa découpe dépendent du système utilisé. (Règle permanente 2)"],
        ["39","La fidélisation d'une clientèle stable repose principalement sur :","Des remises régulières et des programmes de fidélité commerciaux","La qualité constante de la prestation, la clarté de la relation et le soin apporté aux moments de contact","Une présence quotidienne sur les réseaux sociaux","L'offre du tarif le plus compétitif de la zone","B","La relation régulière, honnête et de qualité constante est ce qui stabilise une clientèle — au-delà des outils marketing. (Module 11)"],
        ["40","Lors d'une observation en cours de prestation, la formulation correcte est :","\"Tu as une infection sur cet ongle.\"","\"Je vois ce qui ressemble à quelque chose de grave.\"","\"J'observe un décollement localisé et une modification de couleur sur cet ongle — je préfère m'arrêter ici.\"","\"Ton ongle est abîmé — tu as dû le traumatiser.\"","C","Décrire uniquement ce qui est visible, sans nommer ni interpréter. La formulation est calme et descriptive. (Règle permanente 4 & 5)"],
        ["41","La conversion de l'objectif de rémunération mensuelle en taux horaire dépend :","D'une formule universelle valable pour tous les statuts","Du statut juridique, du régime fiscal et des cotisations applicables — à adapter selon sa situation","Uniquement du nombre d'heures travaillées par semaine","Du tarif moyen du marché local","B","La conversion net/brut ou la prise en compte des cotisations varie selon le statut et le pays — un accompagnement comptable est recommandé pour l'intégrer correctement. (Module 10)"]
      ]},
      {"type":"info","content":"Barème de validation du parcours pédagogique Nahira Academy (seuil minimum : 14/20) :\n— 18–20 : excellente maîtrise de l'ensemble des notions\n— 14–17 : parcours pédagogique validé — quelques points à consolider\n— 10–13 : révision recommandée — parcours non encore validé\n— 0–9 : bases à retravailler — parcours non encore validé\n\nCe seuil est un critère pédagogique interne — il ne constitue ni un diplôme, ni une certification professionnelle reconnue par une autorité publique. Les explications de chaque question indiquent quel module approfondir. Les tentatives sont illimitées."}
    ]$cb$
  );

END;
$m12$;

-- ══════════════════════════════════════════════════════════════════

DO $m13$
DECLARE
  cid UUID;
  mid UUID;
BEGIN
  SELECT id INTO cid FROM academy_courses WHERE slug = 'fiber-signature' LIMIT 1;

  INSERT INTO academy_modules (course_id, title, sort_order)
  VALUES (cid, 'Clôture & Attestation de formation', 13)
  RETURNING id INTO mid;

  -- M13.L1 — Récapitulatif des compétences acquises
  INSERT INTO academy_lessons (module_id, course_id, title, sort_order, duration_minutes, content_blocks)
  VALUES (mid, cid, 'Récapitulatif des compétences acquises', 1, 10,
    $cb$[
      {"type":"section","label":"Ce que tu maîtrises désormais"},
      {"type":"table","headers":["Domaine","Compétences"],"rows":[
        ["Fondamentaux & matières","Structure de l'ongle naturel · Composition et rôle de la fibre de verre · Systèmes de gel et produits associés · Instructions fabricant et priorité de leurs protocoles"],
        ["Préparation & hygiène","Protocole de préparation de la plaque naturelle · Hygiène professionnelle et prévention des contaminations · Usage adapté des grains de lime (valeurs indicatives) · Gestion du matériel et des consommables"],
        ["Technique de pose","Pose de la fibre et du gel selon le système utilisé · Principe d'absence de contact produit/peau · Architecture adaptée à la plaque et à la longueur · Polymérisation selon les instructions fabricant"],
        ["Observation & conduite professionnelle","Observation descriptive des signes unguéaux · Conduite face à un signe d'alerte : évaluation, adaptation, report · Orientation vers un professionnel de santé si nécessaire · Évaluation globale avant décision sur les autres ongles"],
        ["Business & gestion","Structure d'offre de prestations · Méthode de calcul de base tarifaire indicative · Gestion du temps et rentabilité · Fiche cliente, traçabilité, données personnelles"],
        ["Communication cliente","Consultation initiale et objectif partagé · Communication pendant la prestation · Annonce d'une observation difficile ou d'un refus · Gestion des retours et fidélisation"]
      ]},
      {"type":"info","content":"À garder en tête :\n— Les instructions du fabricant priment sur toute recommandation générale de la formation\n— Les valeurs techniques (grains, temps, marges) sont données à titre indicatif — elles s'adaptent à la situation et au matériel\n— L'observation descriptive et la décision professionnelle sont distinctes du diagnostic médical\n— La compétence technique s'affine avec la pratique régulière et la formation continue"}
    ]$cb$
  );

  -- M13.L2 — Les fiches pratiques — F1 à F12
  INSERT INTO academy_lessons (module_id, course_id, title, sort_order, duration_minutes, content_blocks)
  VALUES (mid, cid, 'Les fiches pratiques — F1 à F12', 2, 10,
    $cb$[
      {"type":"section","label":"Toutes les fiches de la formation"},
      {"type":"text","content":"Les fiches F1 à F12 sont les documents pratiques de référence de la Masterclass Fiber Signature. Elles sont téléchargeables depuis l'Atelier Nahira en format digital interactif et en format imprimable."},
      {"type":"table","headers":["Fiche","Titre","Description"],"rows":[
        ["F1","Protocole de préparation","Étapes de préparation de la plaque naturelle avant toute pose · ordre des étapes · points de vigilance"],
        ["F2","Protocole de pose — fibre de verre","Déroulement de la pose étape par étape · paramètres à adapter selon le système fabricant"],
        ["F3","Accord de prestation esthétique","Document d'information et d'accord à compléter avec la cliente · à adapter selon le cadre légal applicable"],
        ["F4","Protocole de dépose","Dépose par acétone et par limage · évaluation de la plaque après dépose · décision de repose"],
        ["F5","Guide des grains — usages et adaptations","Valeurs indicatives par étape · principe d'adaptation au matériel et aux instructions fabricant"],
        ["F6","Références produits & compatibilités","Types de produits utilisés en pose fibre de verre · rôles respectifs · importance des instructions fabricant"],
        ["F7","Protocole d'hygiène & désinfection","Gestion du matériel, des consommables et du poste de travail · prévention de la contamination croisée"],
        ["F8","Calculateur de tarif","Tableau de calcul de la base tarifaire indicative · 4 composantes · à compléter avec ses propres données"],
        ["F9","Modèle de menu de prestations","Structure du menu · noms de prestations · durées estimées · à personnaliser selon son offre"],
        ["F10","Messages de suivi client","Modèles de messages post-prestation, de rappel de rendez-vous et de réponse aux avis · à adapter à son style"],
        ["F11","Protocole de rééquilibrage","Évaluation de la pose existante · traitement des soulèvements · préparation et repose sur repousse"],
        ["F12","Guide d'observation & conduite professionnelle","Signes à observer · conduite appropriée par situation · formulations d'annonce et de refus"]
      ]},
      {"type":"tip","content":"Imprimer ou enregistrer les fiches F1, F2 et F7 dans l'espace de travail, et les fiches F3, F8, F9 dans un dossier administratif accessible rapidement. Les fiches F12 et F5 sont utiles à portée de main lors de la formation continue et des nouvelles situations rencontrées."}
    ]$cb$
  );

  -- M13.L3 — Attestation de suivi et de validation du parcours pédagogique privé
  INSERT INTO academy_lessons (module_id, course_id, title, sort_order, duration_minutes, content_blocks)
  VALUES (mid, cid, 'Attestation de suivi et de validation du parcours pédagogique privé', 3, 5,
    $cb$[
      {"type":"section","label":"Document d'attestation"},
      {"type":"text","content":"L'attestation est un document interne Nahira Academy qui atteste du suivi et de la validation du parcours pédagogique interne de la Masterclass Fiber Signature. Elle n'est pas un titre professionnel réglementé.\n\nCondition de délivrance : avoir obtenu au minimum 14/20 au quiz final (Module 12)."},
      {"type":"text","content":"🔒 Attestation verrouillée — 14 / 20 minimum\nL'attestation est accessible après obtention du seuil de validation au quiz final (Module 12). Les tentatives sont illimitées."},
      {"type":"text","content":"Nahira Academy — Masterclass\nAttestation de suivi et de validation du parcours pédagogique privé\nFiber Signature — Masterclass en pose de fibre de verre\n\nJe soussignée Nahira, fondatrice de Nahira Academy, atteste que\n[ Prénom Nom de la participante ]\na suivi l'intégralité de la Masterclass Fiber Signature et satisfait aux critères pédagogiques internes de validation du parcours, comprenant 13 modules couvrant la technique, l'hygiène, la conduite professionnelle, la gestion d'activité et la communication cliente.\n\nDate de délivrance : ___________________________\n\nCette attestation est un document privé délivré par Nahira Academy. Elle ne constitue ni un diplôme d'État, ni un titre professionnel, ni une certification professionnelle reconnue ou enregistrée par une autorité publique.\n\nNahira — Fondatrice, Nahira Academy"},
      {"type":"text","content":"Pour imprimer : utiliser la fonction d'impression du navigateur · orientation portrait · enlever les en-têtes et pieds de page"},
      {"type":"info","content":"Cette attestation est un document privé délivré par Nahira Academy. Elle ne constitue ni un diplôme d'État, ni un titre professionnel, ni une certification professionnelle reconnue ou enregistrée par une autorité publique. Pour l'exercice à titre professionnel, vérifier les qualifications requises par la réglementation applicable dans son pays et son lieu d'exercice."}
    ]$cb$
  );

  -- M13.L4 — Prochaines étapes
  INSERT INTO academy_lessons (module_id, course_id, title, sort_order, duration_minutes, content_blocks)
  VALUES (mid, cid, 'Prochaines étapes', 4, 10,
    $cb$[
      {"type":"section","label":"Mettre en pratique"},
      {"type":"step","number":1,"title":"Consolider la technique","content":"Réaliser les premières poses sur des modèles volontaires avant toute activité commerciale — et chronométrer pour ajuster les durées réelles. Tout exercice professionnel ou commercial reste soumis aux qualifications et règles applicables localement."},
      {"type":"step","number":2,"title":"Compléter les fiches","content":"Remplir la Fiche F8 (calculateur de tarif) et la Fiche F9 (menu de prestations) avec ses propres données avant d'ouvrir sa liste de clientes."},
      {"type":"step","number":3,"title":"Se renseigner sur son cadre légal","content":"Vérifier les obligations applicables (affichage des prix, données clients, qualifications requises) selon son statut et son pays d'exercice."},
      {"type":"step","number":4,"title":"Continuer à se former","content":"Suivre les évolutions des systèmes et des produits utilisés. Chaque nouveau fabricant ou système demande une lecture des instructions spécifiques."},
      {"type":"step","number":5,"title":"Observer et documenter","content":"Utiliser la fiche cliente à chaque prestation dès le départ. La traçabilité dès les premières clientes est plus facile à maintenir qu'à rattraper."},
      {"type":"step","number":6,"title":"Rejoindre la communauté Nahira","content":"Partager ses questions, ses avancées et ses cas pratiques avec les autres participantes — la progression en communauté est plus rapide et plus riche."},
      {"type":"tip","content":"La formation t'a donné les bases — la pratique te donnera le reste. Chaque ongle est une nouvelle situation, chaque cliente une nouvelle conversation. Ce qui distingue une bonne professionnelle, c'est moins la rapidité que la rigueur : observer avant d'agir, expliquer plutôt que présumer, et continuer à apprendre."},
      {"type":"je_maitrise","items":["Je peux décrire un signe unguéal sans en établir la cause","Je connais les 4 composantes de ma base tarifaire et je les ai calculées pour mes principales prestations","Je sais annoncer un refus ou une adaptation en 3 temps, calmement et sans s'excuser à l'excès","Ma fiche cliente est prête et ma Fiche F3 est adaptée à mon cadre d'exercice","Je sais à qui m'adresser (professionnel de santé, chambre professionnelle, expert-comptable) selon la situation rencontrée"]}
    ]$cb$
  );

END;
$m13$;
